/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicWorkoutRouteImport } from './routes/api/public/workout'
import { Route as ApiPublicSimulationRouteImport } from './routes/api/public/simulation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkoutRoute = ApiPublicWorkoutRouteImport.update({
  id: '/api/public/workout',
  path: '/api/public/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSimulationRoute = ApiPublicSimulationRouteImport.update({
  id: '/api/public/simulation',
  path: '/api/public/simulation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/simulation': typeof ApiPublicSimulationRoute
  '/api/public/workout': typeof ApiPublicWorkoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/simulation': typeof ApiPublicSimulationRoute
  '/api/public/workout': typeof ApiPublicWorkoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/simulation': typeof ApiPublicSimulationRoute
  '/api/public/workout': typeof ApiPublicWorkoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/simulation' | '/api/public/workout'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/simulation' | '/api/public/workout'
  id: '__root__' | '/' | '/api/public/simulation' | '/api/public/workout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicSimulationRoute: typeof ApiPublicSimulationRoute
  ApiPublicWorkoutRoute: typeof ApiPublicWorkoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/workout': {
      id: '/api/public/workout'
      path: '/api/public/workout'
      fullPath: '/api/public/workout'
      preLoaderRoute: typeof ApiPublicWorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/simulation': {
      id: '/api/public/simulation'
      path: '/api/public/simulation'
      fullPath: '/api/public/simulation'
      preLoaderRoute: typeof ApiPublicSimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicSimulationRoute: ApiPublicSimulationRoute,
  ApiPublicWorkoutRoute: ApiPublicWorkoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
